--query 1
create or replace trigger trg_students_name_uppercase
before insert on students
for each row
begin
  if :new.name is not null then
    :new.name := upper(:new.name);
  end if;
end;
/

--query 2
-- prevents delete on employees on saturday or sunday 
create or replace trigger trg_prevent_delete_employees_weekend
before delete on employees
for each row
begin
  if lower(trim(to_char(sysdate, 'fmday', 'nls_date_language=english'))) in ('saturday','sunday') then
    raise_application_error(-20001, 'deletions are not allowed on weekends');
  end if;
end;
/

-- create audit table
create table log_salary_audit (
  id             number generated by default as identity,
  employee_id    number,
  old_salary     number,
  new_salary     number,
  changed_by     varchar2(100),
  changed_at     timestamp,
  comment_text   varchar2(4000)
);

create or replace trigger trg_audit_salary_updates
after update of salary on employees
for each row
declare
  v_user varchar2(100);
begin
  v_user := sys_context('userenv','session_user');
  insert into log_salary_audit(employee_id, old_salary, new_salary, changed_by, changed_at)
  values(:old.employee_id, :old.salary, :new.salary, v_user, systimestamp);
end;
/
create or replace trigger trg_no_negative_price_products
before update of price on products
for each row
begin
  if :new.price is not null and :new.price < 0 then
    raise_application_error(-20002, 'price cannot be negative');
  end if;
end;
/

create or replace trigger trg_courses_set_creator
before insert on courses
for each row
begin
  if :new.created_by is null then
    :new.created_by := sys_context('userenv','session_user');
  end if;
  if :new.created_at is null then
    :new.created_at := systimestamp;
  end if;
end;
/

-- choose whatever default department id
create or replace trigger trg_emp_set_default_dept
before insert on emp
for each row
begin
  if :new.department_id is null then
    :new.department_id := 1;
  end if;
end;
/

-- audit table to store totals after bulk insert operations
create table sales_total_audit (
  id           number generated by default as identity,
  total_amount number,
  row_count    number,
  created_at   timestamp
);

create or replace trigger trg_sales_compound_total
for insert on sales
compound trigger

  g_total number := 0;
  g_count number := 0;

  before statement is
  begin
    g_total := 0;
    g_count := 0;
  end before statement;

  before each row is
  begin
    -- assume sales has columns quantity and unit_price
    if :new.quantity is not null and :new.unit_price is not null then
      g_total := g_total + (:new.quantity * :new.unit_price);
      g_count := g_count + 1;
    end if;
  end before each row;

  after statement is
  begin
    -- store aggregate result after the bulk insert
    insert into sales_total_audit(total_amount, row_count, created_at)
    values(g_total, g_count, systimestamp);
  end after statement;

end trg_sales_compound_total;
/

-- create log table for DDL events
create table schema_ddl_log (
  id            number generated by default as identity,
  username      varchar2(100),
  event         varchar2(30),
  object_type   varchar2(100),
  object_name   varchar2(400),
  sql_text      clob,
  event_time    timestamp
);

create or replace trigger trg_schema_ddl_audit
after ddl on schema
declare
  v_sql   varchar2(4000);
  v_text  clob;
  i       pls_integer := 1;
begin
  if ora_sysevent in ('create','drop') then
    v_text := null;
    begin
      loop
        v_sql := ora_sql_txt(i);
        exit when v_sql is null;
        v_text := nvl(v_text, '') || v_sql || chr(10);
        i := i + 1;
      end loop;
    exception
      when others then
        null; 
    end;

    insert into schema_ddl_log(username, event, object_type, object_name, sql_text, event_time)
    values(
      sys_context('userenv','session_user'),
      ora_sysevent,
      ora_dict_obj_type,
      ora_dict_obj_name,
      v_text,
      systimestamp
    );
  end if;
end;
/

create or replace trigger trg_prevent_update_shipped_orders
before update on orders
for each row
begin
  if :old.order_status is not null and upper(:old.order_status) = 'SHIPPED' then
    raise_application_error(-20003, 'cannot update an order that is already shipped');
  end if;
end;
/

-- create login_audit table
create table login_audit (
  id         number generated by default as identity,
  username   varchar2(100),
  osuser     varchar2(100),
  userhost   varchar2(100),
  logon_time timestamp
);

create or replace trigger trg_login_audit
after logon on database
declare
  v_user varchar2(100);
begin
  v_user := sys_context('userenv','session_user');
  insert into login_audit(username, osuser, userhost, logon_time)
  values(v_user, sys_context('userenv','os_user'), sys_context('userenv','host'), systimestamp);
exception
  when others then
    null; 
end;
/

