---Post Lab Tasks (Lab 5)
---Layyana Junaid 23k-0056
-- Employees table with manager relationship
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    SALARY DECIMAL(10,2),
    HIRE_DATE DATE,
    DEPT_ID INT,
    MANAGER_ID INT,
    CITY VARCHAR(50)
);

-- Students table with city
CREATE TABLE STUDENTS (
    STUD_ID INT PRIMARY KEY,
    STUD_NAME VARCHAR(100),
    AGE INT,
    DEPT_ID INT,
    CITY VARCHAR(50)
);

-- Faculty/Teachers table
CREATE TABLE FACULTY (
    FACULTY_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    SALARY DECIMAL(10,2),
    HIRE_DATE DATE,
    DEPT_ID INT,
    CITY VARCHAR(50)
);

-- Teaches relationship
CREATE TABLE TEACHES (
    FACULTY_ID INT,
    COURSE_ID INT,
    PRIMARY KEY (FACULTY_ID, COURSE_ID)
);

SELECT s.STUD_NAME, f.NAME AS TEACHER_NAME, s.CITY
FROM STUDENTS s
JOIN FACULTY f ON s.CITY = f.CITY;

SELECT e.NAME AS EMPLOYEE_NAME, m.NAME AS MANAGER_NAME
FROM EMPLOYEES e
LEFT JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID;

SELECT EMPLOYEE_ID, NAME
FROM EMPLOYEES
WHERE DEPT_ID IS NULL;

SELECT d.DEPT_NAME, AVG(e.SALARY) AS AVG_SALARY
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPT_ID = d.DEPT_ID
GROUP BY d.DEPT_ID, d.DEPT_NAME
HAVING AVG(e.SALARY) > 50000;

SELECT e.NAME, e.SALARY, d.DEPT_NAME
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPT_ID = d.DEPT_ID
WHERE e.SALARY > (
    SELECT AVG(SALARY) 
    FROM EMPLOYEES 
    WHERE DEPT_ID = e.DEPT_ID
);

SELECT d.DEPT_NAME
FROM DEPARTMENTS d
WHERE NOT EXISTS (
    SELECT 1 
    FROM EMPLOYEES e 
    WHERE e.DEPT_ID = d.DEPT_ID AND e.SALARY < 30000
);

SELECT s.STUD_NAME, c.COURSE_NAME
FROM STUDENTS s
JOIN ENROLLMENT e ON s.STUD_ID = e.STUDENT_ID
JOIN COURSE c ON e.COURSE_ID = c.COURSE_ID
WHERE s.CITY = 'Lahore';

SELECT e.NAME AS EMPLOYEE_NAME, 
       m.NAME AS MANAGER_NAME, 
       d.DEPT_NAME,
       e.HIRE_DATE
FROM EMPLOYEES e
LEFT JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID
JOIN DEPARTMENTS d ON e.DEPT_ID = d.DEPT_ID
WHERE e.HIRE_DATE BETWEEN '2020-01-01' AND '2023-01-01';

SELECT s.STUD_NAME, c.COURSE_NAME
FROM STUDENTS s
JOIN ENROLLMENT e ON s.STUD_ID = e.STUDENT_ID
JOIN COURSE c ON e.COURSE_ID = c.COURSE_ID
JOIN TEACHES t ON c.COURSE_ID = t.COURSE_ID
JOIN FACULTY f ON t.FACULTY_ID = f.FACULTY_ID
WHERE f.NAME = 'Sir Ali';

SELECT e.NAME AS EMPLOYEE_NAME, 
       m.NAME AS MANAGER_NAME, 
       d.DEPT_NAME
FROM EMPLOYEES e
JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID
JOIN DEPARTMENTS d ON e.DEPT_ID = d.DEPT_ID
WHERE e.DEPT_ID = m.DEPT_ID;
